config/routes.rb
Rails.application.routes.draw do
  resources :posts

  devise_for :users

  root 'home#index'

  get 'newsfeed', to: 'home#newsfeed', as: :newsfeed
  get 'friends', to: 'home#friends', as: :friends
  get 'profile', to: 'home#profile', as: :profile

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

# post: user_id: 5, content: "Hello"
# user: id: 5

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to newsfeed_path if current_user
  end

  def newsfeed
    @users = User.all.order(created_at: :desc)
    @posts = Post.all
  end

  def friends
    @users = User.all
  end

  def profile
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
    respond_with(@posts)
  end

  def show
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/friends.haml
- @body_classes = "friends"

%h1 Friends
- @users.each do|user|
  %p= user.email

app/views/home/index.haml
- @body_classes = "index"

%h1 Welcome to facebook
%p Find me in app/views/home/index.html.erb

= link_to "Login", new_user_session_path
= link_to "Sign up", new_user_registration_path

app/views/home/newsfeed.haml
- @body_classes = "newsfeed"

%h1 Newsfeed
- @posts.each do |post|
 %p= "#{post.content} by #{post.user.email}"
- @users.each do |user|
 %p= "#{user.email} signed up at #{user.created_at}"

app/views/home/profile.haml
- @body_classes = "profile"

%h1 Profile
%h2= current_user.email if current_user

app/views/layouts/_footer.haml
.footer
  %h1 painful 2014.10.25

app/views/layouts/_navigation.haml
.navigation
  = link_to "Newsfeed", newsfeed_path
  = link_to "friends", friends_path
  = link_to "profile", profile_path
  = link_to "posts", posts_path

app/views/layouts/_title_bar.haml
.title-bar
  %h1= link_to :Facebook, root_path

  .links
    = link_to :Logout, destroy_user_session_path, method: :delete

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title YuFacebook
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags

  %body{class: @body_classes}
    = render "layouts/title_bar"
    - if current_user 
      = current_user.email 

    = render "layouts/navigation"

    = yield

    = render "layouts/footer"

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_field :content

  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %tr
    %th Content
    %th User
    %th
    %th
    %th

  - @posts.each do |post|
    %tr
      %td= post.content
      %td= post.user.email
      %td= link_to 'Show', post
      %td= link_to 'Edit', edit_post_path(post)
      %td= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @post.content
%p
  %b User:
  = @post.user.email

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path